run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/cavoq/PCL

  misspell:
    locale: US

  gosec:
    excludes:
      - G104
      - G304
      - G306

  staticcheck:
    checks:
      - all
      - -SA1019

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - errcheck
