version: 2

project_name: pcl

builds:
  - id: pcl
    main: ./cmd/pcl
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos: [linux, darwin]
    goarch: [amd64, arm64]

dist: dist